package io.github.NationArchitect.model.component;

import io.github.NationArchitect.model.metric.MetricType;
import io.github.NationArchitect.model.product.ProductType;

import java.util.EnumMap;

/**
 * Defines the contract implemented by all building type enums.
 */
public interface BuildingType {

    /**
     * Returns the enum name of the building type.
     *
     * @return building type name
     */
    public String getName();

    /**
     * Returns the construction cost of the building.
     *
     * @return construction cost
     */
    public double getConstructionCost();

    /**
     * Returns the recurring maintenance cost of the building.
     *
     * @return maintenance cost
     */
    public double getMaintenanceCost();

    /**
     * Returns metric effects provided by the building.
     *
     * @return metric effect map
     */
    public EnumMap<MetricType, Double> getRelatedMetrics();

    /**
     * Returns component effects provided by the building.
     *
     * @return component effect map, or {@code null} if none exists
     */
    public EnumMap<ComponentType, Double> getRelatedComponents();

    /**
     * Returns the land occupied by the building.
     *
     * @return occupied land
     */
    public double getOccupiedLand();

    /**
     * Returns the performance multiplier granted by the building.
     *
     * @return performance multiplier
     */
    public double getPerformanceMultiplier();

    /**
     * Returns direct production generated by the building.
     *
     * @return if building type is one of the industry related building types, {@link WaterManagementBuilding} or {@link ElectricityBuilding}
     * production amount, otherwise 0
     */
    public double getProduction();

    /**
     * Returns the input demand required by the building.
     */
    public EnumMap<ProductType, Double> getDemand();

    /**
     * Returns the building description.
     *
     * @return description text
     */
    public String getDescription();

    /**
     * Returns the maximum worker capacity of the building.
     *
     * @return maximum worker amount
     */
    public int getMaxWorkerAmount();

    /** Returns the maximum human capacity of the building.
     *
     * @return if building type is {@link HealthServicesBuilding} or {@link EducationBuilding} maximum human capacity,
     * otherwise 0
     */
    public int getCapacity();
}
