package io.github.NationArchitect.model.component;

import io.github.NationArchitect.model.metric.MetricType;
import io.github.NationArchitect.model.product.ProductType;

import java.util.EnumMap;

/**
 * Represents the buildings that can be constructed to increase component performances,
 * enhance metrics or manufacture products for country to use or sell.
 */
public class Building {

    private static final double MAINTENANCE_COST_MULTIPLIER = 0.30;

    /** Name of the building. */
    private String name;

    /** Description of the building. */
    private final String description;

    /** Type definition backing this building. */
    private final BuildingType type;

    /** Up-front construction cost. */
    private final double constructionCost;

    /** Recurring maintenance cost. */
    private final double maintenanceCost;

    /** Metric effects granted by the building. */
    private final EnumMap<MetricType, Double> relatedMetrics;

    /** Component effects granted by the building. */
    private final EnumMap<ComponentType, Double> relatedComponents;

    /** Land area occupied by the building. */
    private final double occupiedLand;

    /** The building efficiency */
    private double efficiency;

    /** Performance multiplier applied by the building. */
    private double performanceMultiplier;

    /** Product demand generated by the building. */
    private final EnumMap<ProductType, Double> demand;

    /** Current number of assigned workers. */
    private int workerAmount;

    /** Maximum worker capacity of the building. */
    private final int maxWorkerAmount;

    /**
     * Creates a building instance from a building type definition.
     *
     * @param name name of the building instance
     * @param type source building type definition
     */
    public Building(String name, BuildingType type) {
        this.name = name;
        this.type = type;
        this.description = type.getDescription();
        this.constructionCost = type.getConstructionCost();
        this.maintenanceCost = type.getMaintenanceCost() * MAINTENANCE_COST_MULTIPLIER;
        this.relatedMetrics = type.getRelatedMetrics() == null
            ? new EnumMap<>(MetricType.class)
            : new EnumMap<>(type.getRelatedMetrics());
        this.relatedComponents = type.getRelatedComponents() == null
            ? new EnumMap<>(ComponentType.class)
            : new EnumMap<>(type.getRelatedComponents());
        this.occupiedLand = type.getOccupiedLand();
        this.performanceMultiplier = type.getPerformanceMultiplier();
        this.demand = type.getDemand() == null ? null : new EnumMap<>(type.getDemand());
        this.maxWorkerAmount = type.getMaxWorkerAmount();
        calculateEfficiency();
    }

    /**
     * Returns the building name.
     *
     * @return building name
     */
    public String getName() {
        return name;
    }

    /**
     * Changes the building name.
     *
     * @param name new building name
     * */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the building description.
     *
     * @return description text
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns the building type definition.
     *
     * @return building type
     */
    public BuildingType getType() {
        return type;
    }

    /**
     * Returns the construction cost.
     *
     * @return construction cost
     */
    public double getConstructionCost() {
        return constructionCost;
    }

    /**
     * Returns the maintenance cost.
     *
     * @return maintenance cost
     */
    public double getMaintenanceCost() {
        return maintenanceCost;
    }

    /**
     * Returns metric effects of the building.
     *
     * @return copy of related metric effects
     */
    public EnumMap<MetricType, Double> getRelatedMetrics() {
        return new EnumMap<>(relatedMetrics);
    }

    /**
     * Returns component effects of the building.
     *
     * @return copy of related component effects
     */
    public EnumMap<ComponentType, Double> getRelatedComponents() {
        return new EnumMap<>(relatedComponents);
    }

    /**
     * Returns occupied land.
     *
     * @return occupied land
     */
    public double getOccupiedLand() {
        return occupiedLand;
    }

    /**
     * Returns the building efficiency.
     *
     * @return building efficiency
     */
    public double getEfficiency() {
        return efficiency;
    }

    /** Calculates the building efficiency by expressing the number of workers as a ratio of the maximum worker capacity. */
    public void calculateEfficiency() {
        efficiency = (double) workerAmount / maxWorkerAmount;
        performanceMultiplier *= efficiency;
        EnumMap<MetricType, Double> baseRelatedMetrics = type.getRelatedMetrics() == null
            ? new EnumMap<>(MetricType.class)
            : type.getRelatedMetrics();
        EnumMap<ComponentType, Double> baseRelatedComponents = type.getRelatedComponents() == null
            ? new EnumMap<>(ComponentType.class)
            : type.getRelatedComponents();
        relatedMetrics.replaceAll((t, v) -> baseRelatedMetrics.getOrDefault(t, 0.0) * efficiency);
        relatedComponents.replaceAll((t, v) -> baseRelatedComponents.getOrDefault(t, 0.0) * efficiency);
    }

    /**
     * Returns performance multiplier granted by the building.
     *
     * @return performance multiplier
     */
    public double getPerformanceMultiplier() {
        return performanceMultiplier;
    }

    /**
     * Returns product demand created by the building.
     *
     * @return copy of demand map, or {@code null} if the building has no demand
     */
    public EnumMap<ProductType, Double> getDemand() {
        return demand == null ? null : new EnumMap<>(demand);
    }

    /**
     * Returns the number of assigned workers.
     *
     * @return worker amount
     */
    public int getWorkerAmount() {
        return workerAmount;
    }

    public void setWorkerAmount(int workerAmount) {
        this.workerAmount = Math.max(0, Math.min(workerAmount, maxWorkerAmount));
        calculateEfficiency();
    }

    /**
     * Increases assigned worker count.
     *
     * @param amount amount to add
     */
    void hireWorker(int amount) {
        workerAmount += amount;
        calculateEfficiency();
    }

    /**
     * Decreases assigned worker count without going below zero.
     *
     * @param amount amount to remove
     */
    void fireWorker(int amount) {
        workerAmount = Math.max(0, workerAmount - amount);
        calculateEfficiency();
    }

    /**
     * Returns the maximum worker capacity.
     *
     * @return max worker amount
     */
    public int getMaxWorkerAmount() {
        return maxWorkerAmount;
    }
}
