package io.github.NationArchitect.model.component;

import io.github.NationArchitect.model.land.Region;
import io.github.NationArchitect.model.product.ProductType;

/**
 * Base class for components that directly produce a tradable product.
 */
public abstract class ManufacturerComponent extends Component {

    /** Current production amount generated by the component. */
    private int productionAmount;

    /** Product type produced by this manufacturer component. */
    private final ProductType productType;

    /**
     * Creates a manufacturer component for the given component and product types.
     *
     * @param componentType logical type of the component
     * @param productType product generated by the component
     * @param region region that owns the component
     */
    public ManufacturerComponent(ComponentType componentType, ProductType productType, Region region) {
        super(componentType, region);
        this.productType = productType;
    }

    @Override
    public void constructBuilding(Building building) {
        super.constructBuilding(building);
        productionAmount += (int) building.getType().getProduction();
    }

    /**
     * Returns the current production amount.
     *
     * @return production amount
     */
    public int getProductionAmount() {
        return productionAmount;
    }

    /**
     * Returns the type of product.
     *
     * @return type of product
     */
    public ProductType getProductType() {
        return productType;
    }
}
